version: "2"
linters:
  default: fast
  enable:
    - perfsprint
    - staticcheck
    - unconvert
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  disable:
    - cyclop
    - depguard
    - dupl
    - funlen
    - gocognit
    - gocyclo
    - godoclint
    - godox
    - lll
    - maintidx
    - mnd
    - nestif
    - wsl
